@file:Suppress("UnstableApiUsage")

package com.autonomousapps

import com.autonomousapps.internal.ClassSetReader
import com.autonomousapps.internal.JarReader
import org.gradle.api.DefaultTask
import org.gradle.api.Task
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.model.ObjectFactory
import org.gradle.api.tasks.*
import org.gradle.workers.WorkAction
import org.gradle.workers.WorkParameters
import org.gradle.workers.WorkerExecutor
import java.io.File
import javax.inject.Inject

interface ClassAnalysisTask : Task {
    @get:OutputFile
    val output: RegularFileProperty
}

/**
 * Produces a report of all classes referenced by a given jar.
 */
@CacheableTask
open class JarAnalysisTask @Inject constructor(
    private val objects: ObjectFactory,
    private val workerExecutor: WorkerExecutor
) : DefaultTask(), ClassAnalysisTask {

    init {
        group = "verification"
        description = "Produces a report of all classes referenced by a given jar"
    }

    @get:Classpath
    val jar: RegularFileProperty = objects.fileProperty()

    /**
     * Java source files. Stubs generated by the kotlin-kapt plugin.
     */
    @PathSensitive(PathSensitivity.RELATIVE)
    @get:InputFiles
    val kaptJavaStubs: ConfigurableFileCollection = objects.fileCollection()

    /**
     * Android layout XML files.
     */
    @PathSensitive(PathSensitivity.RELATIVE)
    @get:InputFiles
    val layoutFiles: ConfigurableFileCollection = objects.fileCollection()

    @get:OutputFile
    override val output: RegularFileProperty = objects.fileProperty()

    internal fun layouts(files: List<File>) {
        for (file in files) {
            layoutFiles.from(
                // TODO Gradle 6 can do objects.fileTree().from(file)
                objects.fileCollection().from(file).asFileTree
                    .matching {
                        include { it.path.contains("layout") }
                    }.files
            )
        }
    }

    @TaskAction
    fun action() {
        val reportFile = output.get().asFile

        // Cleanup prior execution
        reportFile.delete()

        val jarFile = jar.get().asFile

        workerExecutor.noIsolation().submit(JarAnalysisWorkAction::class.java) {
            jar = jarFile
            kaptJavaSource = kaptJavaStubs.files
            layouts = layoutFiles.files
            report = reportFile
        }
        workerExecutor.await()

        logger.debug("Report:\n${reportFile.readText()}")
    }
}

interface JarAnalysisParameters : WorkParameters {
    var jar: File
    var kaptJavaSource: Set<File>
    var layouts: Set<File>
    var report: File
}

// TODO this and ClassListAnalysisWorkAction look very similar
abstract class JarAnalysisWorkAction : WorkAction<JarAnalysisParameters> {

    override fun execute() {
        val analyzer = JarReader(
            jarFile = parameters.jar,
            layouts = parameters.layouts,
            kaptJavaSource = parameters.kaptJavaSource
        )

        val classNames = analyzer.analyze()

        parameters.report.writeText(classNames.joinToString(separator = "\n"))
    }
}

/**
 * Produces a report of all classes referenced by a given set of class files.
 */
@CacheableTask
open class ClassListAnalysisTask @Inject constructor(
    private val objects: ObjectFactory,
    private val workerExecutor: WorkerExecutor
) : DefaultTask(), ClassAnalysisTask {

    init {
        group = "verification"
        description = "Produces a report of all classes referenced by a given jar"
    }

    /**
     * Class files generated by Kotlin source.
     */
    @PathSensitive(PathSensitivity.RELATIVE)
    @get:InputFiles
    val kotlinClasses: ConfigurableFileCollection = objects.fileCollection()

    /**
     * Class files generated by Java source.
     */
    @PathSensitive(PathSensitivity.RELATIVE)
    @get:InputFiles
    val javaClasses: ConfigurableFileCollection = objects.fileCollection()

    /**
     * Java source files. Stubs generated by the kotlin-kapt plugin.
     */
    @PathSensitive(PathSensitivity.RELATIVE)
    @get:InputFiles
    val kaptJavaStubs: ConfigurableFileCollection = objects.fileCollection()

    /**
     * Android layout XML files.
     */
    @PathSensitive(PathSensitivity.RELATIVE)
    @get:InputFiles
    val layoutFiles: ConfigurableFileCollection = objects.fileCollection()

    @get:OutputFile
    override val output: RegularFileProperty = objects.fileProperty()

    internal fun layouts(files: List<File>) {
        for (file in files) {
            layoutFiles.from(
                // TODO Gradle 6 can do objects.fileTree().from(file)
                objects.fileCollection().from(file).asFileTree
                    .matching {
                        include { it.path.contains("layout") }
                    }.files
            )
        }
    }

    @TaskAction
    fun action() {
        val reportFile = output.get().asFile

        // Cleanup prior execution
        reportFile.delete()

        val inputClassFiles = javaClasses.asFileTree.plus(kotlinClasses)
            .filter { it.isFile && it.name.endsWith(".class") }
            .files

        workerExecutor.noIsolation().submit(ClassListAnalysisWorkAction::class.java) {
            classes = inputClassFiles
            kaptJavaSource = kaptJavaStubs.files
            layouts = layoutFiles.files
            report = reportFile
        }
        workerExecutor.await()

        logger.debug("Report:\n${reportFile.readText()}")
    }
}

interface ClassListAnalysisParameters : WorkParameters {
    var classes: Set<File>
    var kaptJavaSource: Set<File>
    var layouts: Set<File>
    var report: File
}

// TODO this and JarAnalysisWorkAction look very similar
abstract class ClassListAnalysisWorkAction : WorkAction<ClassListAnalysisParameters> {

    override fun execute() {
        val analyzer = ClassSetReader(
            classes = parameters.classes,
            layouts = parameters.layouts,
            kaptJavaSource = parameters.kaptJavaSource
        )

        val classNames = analyzer.analyze()

        parameters.report.writeText(classNames.joinToString(separator = "\n"))
    }
}
