# Borrowed from https://github.com/gradle/gradle-build-action
name: Test latest Gradle RC

on:
  schedule:
    - cron: 0 0 * * * # daily
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

permissions: {}

jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Setup java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # 6.1.0
        with:
          gradle-version: release-candidate

      # just test build configuration
      - name: Gradle dry run (main)
        run: './gradlew build --dry-run'

      - name: Gradle dry run (testkit)
        run: './gradlew -p testkit/ build --dry-run'
