# Borrowed from https://github.com/gradle/gradle-build-action
name: Test latest Gradle RC

on:
  schedule:
    - cron: 0 0 * * * # daily

jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4.1.1
      - name: Setup java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/gradle-build-action@v3-prerelease
        id: setup-gradle
        with:
          gradle-version: release-candidate
      - run: gradle build --dry-run # just test build configuration
      - run: echo "The release-candidate version was ${{ steps.setup-gradle.outputs.gradle-version }}"
